### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by lux10n** [Categorically/OpenBullet2Python#15]
Hi, I want to translate this block in python

`#Login REQUEST POST "https://example.net/login" 
  CONTENT "i13=0&login<U>&PPSX=&NewUser=1&FoundMSAs=&fspost=0&i21=0&CookieDisclosure=0" 
  CONTENTTYPE "application/x-www-form-urlencoded" 
  HEADER "Host: example.net" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0" 
  HEADER "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" 
  HEADER "Accept-Language: en-US,en;q=0.5" 
  HEADER "Accept-Encoding: gzip, deflate, br" 
  HEADER "Referer: https://example.net/login" 
  HEADER "Content-Type: application/x-www-form-urlencoded" 
  HEADER "Content-Length: 1666" 
  HEADER "Origin: https://example.net" 
  HEADER "DNT: 1" 
  HEADER "Connection: keep-alive" 
  HEADER "Upgrade-Insecure-Requests: 1" `

Can you help me ?

**Comment by WHITEH0ST** [comment]
Hello, Great work on this splendid project but i tried to run example.py file and in requests.py says list object is not subscriptable. 
See reference in image below.
I checked it out on vs code but dont know what to do because its not my code any help
![example ob](https://user-images.githubusercontent.com/79903818/155861990-5f23f33d-0084-4f0a-b121-6ca1e3a1cfa8.png)
